# Deployment configuration

repo-name    = "Foundation-service-control-policies"
part-of      = 'foundation'


[[Script]]
name         = 'sync-scps'
args         = [['--config-dir', '../Installer/apps/foundation/SCPs']]
